server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 30m
  port: 8080

# JSP, mustache 원하는거 사용
#spring:
#  mustache:
#    servlet:
#      expose-session-attributes: true
#      expose-request-attributes: true
 
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: root
    password: asd123
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
      - classpath:db/data.sql
      schema-locations:
      - classpath:db/table.sql
      
#mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml #MyBatis 매퍼 파일 위치를 설정. **은 모든 디렉토리를 의미하며, *.xml은 모든 xml 파일을 의미한다.
  configuration:
    map-underscore-to-camel-case: true #데이터베이스의 언더스코어 네이밍(column_name)을 카멜 케이스(columnName)로 자동 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL 로깅 구현체를 설정합니다. 
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
    
    